name: Publish to GitHub Packages
description: Publishes npm package to GitHub Packages registry with version checking

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  repository-owner:
    description: 'Repository owner (will be lowercased for npm scope)'
    required: true
  package-name:
    description: 'Package name (without scope)'
    required: true
    default: 'ts-ioc-container'

runs:
  using: composite
  steps:
    - name: Publish to GitHub Packages
      shell: bash
      run: ${{ github.action_path }}/publish.sh "${{ inputs.repository-owner }}" "${{ inputs.repository }}" "${{ inputs.package-name }}" "${{ inputs.github-token }}"
