version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: cimg/base:stable

    environment:
      NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}

      - node/install:
          install-yarn: true
          node-version: '18.17.0'

      - run:
          name: Install dependencies
          command: |
            corepack enable
            yarn -v
            yarn install --frozen-lockfile

      - run: npm run build -- --no-progress
      - run: npm run test -- --no-progress

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache

workflows:
  test:
    jobs:
      - test:
          context: my_context
