version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: cimg/base:stable

    environment:
      NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}

      - node/install:
          install-yarn: true
          node-version: '18.17.0'

      - run:
          name: Install dependencies
          command: |
            corepack enable
            yarn -v
            yarn install --immutable

      - run: npm run build

      - run: npm test -- --scope=reactivex-react

      - coveralls/upload:
          coverage_file: ./packages/reactivex-react/coverage/lcov.info
          flag_name: 'reactivex-react'

      - run: npm test -- --scope=ts-request-mediator

      - coveralls/upload:
          coverage_file: ./packages/request-mediator/coverage/lcov.info
          flag_name: 'ts-request-mediator'

      - run: npm test -- --scope=ts-ioc-container

      - coveralls/upload:
          coverage_file: ./packages/ts-ioc-container/coverage/lcov.info
          flag_name: 'ts-io-container'

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache

workflows:
  test:
    jobs:
      - test:
          context: my_context
