version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: cimg/base:stable

    environment:
      NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}

      - node/install:
          install-yarn: true
          node-version: '18.17.0'

      - run:
          name: Yarn Set Version Stable
          command: |
            corepack enable
            yarn -v

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - run:
          name: Build packages
          command: npm run build

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache

workflows:
  test:
    jobs:
      - test:
          context: my_context
