version: 2.1
jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Test @ibabkin/ts-constructor-injector
          command: |
            yarn install
            npm test

workflows:
  test:
    jobs:
      - test
