version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'

      - run: yarn install
      - run: npm run build
      - run: npm run test

workflows:
  test:
    jobs:
      - test
