version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: cimg/base:stable

    environment:
      NODE_ENV: test

    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.20.0'

      - run: yarn install
      - run: npm run build
      - run: npm run test
      - coveralls/upload:
            coverage_file: ./packages/ts-ioc-container/coverage/lcov.info
      - run:
          name: Publish to NPM
          command: |
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm run release

workflows:
  test:
    jobs:
      - test:
          context: my_context
