version: 2.1
orbs:
  test: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Test @ibabkin/ts-constructor-injector
          command: |
            yarn install
            npm run build && npm run test

workflows:
  test:
    jobs:
      - test
