version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2
jobs:
  test:
    docker:
      - image: cimg/base:stable

    environment:
      NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}

      - node/install:
          install-yarn: true
          node-version: '16.20.0'

      - run: yarn install --frozen-lockfile
      - run: npm run build
      - run: npm run test

      - coveralls/upload:
          coverage_file: ./packages/ts-ioc-container/coverage/lcov.info

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  test:
    jobs:
      - test:
          context: my_context
