version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.1.2

executors:
  node-executor:
    docker:
      - image: cimg/base:stable
    environment:
      NODE_ENV: test

jobs:
  test:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}

      - node/install:
          node-version: '22.14.0'

      - run: npm ci

      - run: npm run build

      - run: npm test

      - coveralls/upload:
          coverage_file: ./coverage/lcov.info

      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  test:
    jobs:
      - test:
          context: my_context
