// Generated by `tic build` from ../../tic.config.json. Do not edit by hand.
// Bundle tags: app
import { type IContainer, type IContainerModule } from 'ts-ioc-container';
import { AppBundle } from '@app/di/app.bundle';

export const bundles: IContainerModule[] = [
  new AppBundle(),
];

export class AppGroup implements IContainerModule {
  applyTo(container: IContainer): void {
    for (const bundle of bundles) container.useModule(bundle);
  }
}
