// Generated by `tic build` from ../../dev.bundle.yml. Do not edit by hand.
// Paths: @app/services, ./src/infra
import { type IContainer, type IContainerModule, type IRegistration, Registration } from 'ts-ioc-container';
import { PrettyLogger } from '@app/infra/logging/PrettyLogger.dev';
import { Greeter } from '@app/services/Greeter';

export const registrations: IRegistration[] = [
  Registration.fromClass(PrettyLogger),
  Registration.fromClass(Greeter),
];

export class DevBundle implements IContainerModule {
  applyTo(container: IContainer): void {
    for (const registration of registrations) container.addRegistration(registration);
  }
}
