// Generated by `tic build` from ../../prod.bundle.yml. Do not edit by hand.
// Paths: @app/services, ./src/infra
import { type IContainer, type IContainerModule, type IRegistration, Registration } from 'ts-ioc-container';
import { JsonLogger } from '@app/infra/logging/JsonLogger';
import { Greeter } from '@app/services/Greeter';

export const registrations: IRegistration[] = [
  Registration.fromClass(JsonLogger),
  Registration.fromClass(Greeter),
];

export class ProdBundle implements IContainerModule {
  applyTo(container: IContainer): void {
    for (const registration of registrations) container.addRegistration(registration);
  }
}
