// Generated by `tic build` from ../../test.bundle.yml. Do not edit by hand.
import { type IContainer, type IContainerModule, type IRegistration, Registration } from 'ts-ioc-container';
import { Greeter } from '@app/services/Greeter';
import { MemoryLogger } from '@app/testing/MemoryLogger';

export const registrations: IRegistration[] = [
  Registration.fromClass(Greeter),
  Registration.fromClass(MemoryLogger),
];

export class TestBundle implements IContainerModule {
  applyTo(container: IContainer): void {
    for (const registration of registrations) container.addRegistration(registration);
  }
}
