import { build, TicConfigError } from '../../lib';
import { decorated, TempProject } from '../project';

const bundle = (name: string, tags?: string[], extra: object = {}) => ({
  output: `src/di/${name}.bundle.ts`,
  name,
  namespaces: [`./src/${name}`],
  ...(tags ? { tags } : {}),
  ...extra,
});

describe('Story: Compose bundles into groups', () => {
  let project: TempProject;

  afterEach(() => project?.dispose());

  const buildProject = (options: { check?: boolean } = {}) =>
    build({ config: project.path('tic.config.json'), ...options });

  const create = (config: object, files: Record<string, string> = {}) => {
    project = TempProject.create({
      'tic.config.json': config,
      'src/Core/Logger.ts': decorated('Logger'),
      'src/Stripe/Gateway.ts': decorated('StripeGateway'),
      'src/Fake/Gateway.ts': decorated('FakeGateway'),
      ...files,
    });
  };

  it('writes a group to its output, replacing {name} with the group name', () => {
    create({
      bundles: [bundle('Core', ['production'])],
      groups: [{ name: 'AppGroupProduction', output: './{name}.generated.ts', bundleTags: ['production'] }],
    });

    const { outputs } = buildProject();

    expect(outputs.map((o) => [o.kind, o.bundle])).toEqual([
      ['bundle', 'Core'],
      ['group', 'AppGroupProduction'],
    ]);
    expect(project.read('AppGroupProduction.generated.ts')).toContain(
      'export class AppGroupProduction implements IContainerModule',
    );
  });

  it('applies every bundle carrying at least one of its tags, in config order', () => {
    create({
      bundles: [bundle('Core', ['shared']), bundle('Stripe', ['production']), bundle('Fake', ['development'])],
      groups: [{ name: 'Production', output: 'src/di/{name}.group.ts', bundleTags: ['shared', 'production'] }],
    });

    buildProject();

    expect(project.read('src/di/Production.group.ts')).toBe(
      [
        '// Generated by `tic build` from ../../tic.config.json. Do not edit by hand.',
        '// Bundle tags: shared, production',
        "import { type IContainer, type IContainerModule } from 'ts-ioc-container';",
        "import { Core } from './Core.bundle';",
        "import { Stripe } from './Stripe.bundle';",
        '',
        'export const bundles: IContainerModule[] = [',
        '  new Core(),',
        '  new Stripe(),',
        '];',
        '',
        'export class Production implements IContainerModule {',
        '  applyTo(container: IContainer): void {',
        '    for (const bundle of bundles) container.useModule(bundle);',
        '  }',
        '}',
        '',
      ].join('\n'),
    );
  });

  it('imports bundles sharing a class name under suffixed local names', () => {
    create({
      bundles: [
        bundle('Core', ['production'], { name: 'AppBundle' }),
        bundle('Stripe', ['production'], { name: 'AppBundle' }),
      ],
      groups: [{ name: 'Production', output: 'src/di/{name}.group.ts', bundleTags: ['production'] }],
    });

    buildProject();

    const group = project.read('src/di/Production.group.ts');
    expect(group).toContain("import { AppBundle } from './Core.bundle';");
    expect(group).toContain("import { AppBundle as AppBundle_2 } from './Stripe.bundle';");
    expect(group).toContain('  new AppBundle(),\n  new AppBundle_2(),');
  });

  it('never scans a group output, even inside a namespace', () => {
    create(
      {
        bundles: [bundle('Core', ['production'])],
        groups: [{ name: 'Production', output: 'src/Core/{name}.group.ts', bundleTags: ['production'] }],
      },
      { 'src/Core/Production.group.ts': decorated('Stale') },
    );

    buildProject();

    expect(project.read('src/di/Core.bundle.ts')).not.toContain('Stale');
  });

  it('reports a stale group under --check and leaves a current one untouched', () => {
    create({
      bundles: [bundle('Core', ['production'])],
      groups: [{ name: 'Production', output: 'src/di/{name}.group.ts', bundleTags: ['production'] }],
    });

    expect(buildProject({ check: true }).outputs.map((o) => o.status)).toEqual(['stale', 'stale']);
    buildProject();
    expect(buildProject().outputs.map((o) => o.status)).toEqual(['unchanged', 'unchanged']);
  });

  it.each([
    [{ bundles: [bundle('Core', ['a'])], groups: {} }, 'groups: expected an array'],
    [{ bundles: [bundle('Core', 'a' as never)] }, 'bundles[0].tags: expected an array of strings'],
    [
      { bundles: [bundle('Core', ['a'])], groups: [{ output: 'g.ts', bundleTags: ['a'] }] },
      'groups[0].name: expected a valid identifier',
    ],
    [
      { bundles: [bundle('Core', ['a'])], groups: [{ name: 'G', bundleTags: ['a'] }] },
      'groups[0].output: expected a non-empty string',
    ],
    [
      { bundles: [bundle('Core', ['a'])], groups: [{ name: 'G', output: 'g.ts', bundleTags: [] }] },
      'groups[0].bundleTags: expected a non-empty array of strings',
    ],
    [
      { bundles: [bundle('Core', ['a'])], groups: [{ name: 'G', output: 'g.ts', bundleTags: ['b'] }] },
      'groups[0].bundleTags: no bundle is tagged "b"',
    ],
    [
      {
        bundles: [bundle('Core', ['a'])],
        groups: [{ name: 'Core', output: 'src/di/{name}.bundle.ts', bundleTags: ['a'] }],
      },
      'groups[0].output: also written by bundles[0]',
    ],
    [
      {
        bundles: [bundle('Core', ['a'])],
        groups: [
          { name: 'G', output: 'g.ts', bundleTags: ['a'] },
          { name: 'H', output: './g.ts', bundleTags: ['a'] },
        ],
      },
      'groups[1].output: also written by groups[0]',
    ],
  ])('rejects an invalid config %j naming the field', (config, message) => {
    create(config);

    expect(() => buildProject()).toThrow(TicConfigError);
    expect(() => buildProject()).toThrow(message);
  });
});
