import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { run } from '../../lib';
import { decorated, TempProject } from '../project';

class Io {
  readonly out: string[] = [];
  readonly err: string[] = [];

  constructor(
    readonly cwd: string,
    private readonly input?: string,
  ) {}

  stdout = (line: string) => this.out.push(line);
  stderr = (line: string) => this.err.push(line);
  stdin = () => this.input;
}

describe('Story: Describe the container in a config file (tic CLI)', () => {
  let project: TempProject;

  beforeEach(() => {
    project = TempProject.create({
      'tsconfig.json': { compilerOptions: { paths: { '@app/*': ['./src/*'] } } },
      'app.bundle.json': { glob: { paths: ['@app/services'] } },
      'src/services/Logger.ts': decorated('Logger'),
    });
  });

  afterEach(() => project.dispose());

  it('prints the bundle the config file describes to stdout, and writes nothing', () => {
    const io = new Io(project.root);
    const before = readdirSync(project.root, { recursive: true });

    expect(run(['build', 'app.bundle.json'], io)).toBe(0);
    const bundle = io.out.join('\n');
    expect(bundle).toContain("import { Logger } from '@app/services/Logger';");
    expect(bundle).toContain('export class AppBundle implements IContainerModule');
    expect(readdirSync(project.root, { recursive: true })).toEqual(before);
  });

  it('prints exactly what build() returns, so `tic build app.bundle.json > out.ts` saves it as is', () => {
    const io = new Io(project.root);

    run(['build', 'app.bundle.json'], io);

    expect(`${io.out.join('\n')}\n`).toMatch(/^\/\/ Generated by `tic build`\. Do not edit by hand\.\n[\s\S]*\}\n$/);
    expect(io.out).toHaveLength(1);
  });

  it('reads a YAML config, resolving its paths against the config file', () => {
    project.write('config/prod.bundle.yml', "tsconfig: ../tsconfig.json\nglob:\n  paths: ['../src']\n");
    const io = new Io(project.path('src'));

    expect(run(['build', '../config/prod.bundle.yml'], io)).toBe(0);
    expect(io.out.join('\n')).toContain('export class ProdBundle');
  });

  it.each([
    [['build', 'a.bundle.json', 'b.bundle.json'], 'expected one <config>, got a.bundle.json b.bundle.json'],
    [['build', 'app.bundle.json', '--output', 'x.ts'], "Unknown option '--output'"],
    [['build', 'app.bundle.json', '--check'], "Unknown option '--check'"],
    [['build', 'missing.bundle.json'], 'missing.bundle.json: config file not found'],
    [['build', 'app.bundle.toml'], 'expected a .json, .yaml or .yml config file'],
  ])('rejects %j', (argv, message) => {
    const io = new Io(project.root);

    expect(run(argv, io)).toBe(1);
    expect(io.out).toEqual([]);
    expect(io.err.join('\n')).toContain(message);
  });

  it('never builds from tsconfig.json alone: without a config file or piped config it fails', () => {
    const io = new Io(project.root);

    expect(run(['build'], io)).toBe(1);
    expect(io.out).toEqual([]);
    expect(io.err.join('\n')).toContain('missing <config>: name a config file, or pipe one in');
  });

  it.each([
    [['build'], "name: app\nglob:\n  paths: ['@app/services']\n"],
    [['build', '-'], "name: app\nglob:\n  paths: ['@app/services']\n"],
    [['build'], JSON.stringify({ name: 'app', glob: { paths: ['@app/services'] } })],
  ])('reads a piped config from stdin with %j: cat app.bundle.yml | tic build > out.ts', (argv, input) => {
    const io = new Io(project.root, input);

    expect(run(argv, io)).toBe(0);
    expect(io.out.join('\n')).toContain('export class AppBundle implements IContainerModule');
    expect(io.out.join('\n')).toContain("import { Logger } from '@app/services/Logger';");
  });

  it('resolves a piped config against the working directory', () => {
    const io = new Io(project.path('src'), "name: app\ntsconfig: ../tsconfig.json\nglob:\n  paths: ['./services']\n");

    expect(run(['build'], io)).toBe(0);
    expect(io.out.join('\n')).toContain('Registration.fromClass(Logger)');
  });

  it('requires a name in a piped config: there is no file name to take it from', () => {
    const io = new Io(project.root, "glob:\n  paths: ['@app/services']\n");

    expect(run(['build'], io)).toBe(1);
    expect(io.err).toEqual(['tic: <stdin>: name: required for a config read from stdin']);
  });

  it('reports a config error on stderr, naming the config, and prints nothing', () => {
    project.write('app.bundle.json', { output: 'x.ts', glob: { paths: ['@app/services'] } });
    const io = new Io(project.root);

    expect(run(['build', 'app.bundle.json'], io)).toBe(1);
    expect(io.out).toEqual([]);
    expect(io.err).toEqual(['tic: app.bundle.json: output: unknown field']);
  });

  it('fails when a selected class is not covered by a tsconfig alias', () => {
    project.write('app.bundle.json', { glob: { paths: ['./lib'] } });
    project.write('lib/External.ts', decorated('External'));
    const io = new Io(project.root);

    expect(run(['build', 'app.bundle.json'], io)).toBe(1);
    expect(io.err.join('\n')).toContain('no tsconfig paths alias covers lib/External.ts');
  });

  it('prints warnings to stderr, never into the bundle on stdout', () => {
    project.write('app.bundle.json', { glob: { paths: ['@app/services'], exclude: ['legacy/**'] } });
    const io = new Io(project.root);

    expect(run(['build', 'app.bundle.json'], io)).toBe(0);
    expect(io.err.join('\n')).toContain('tic: warning: app.bundle.json: glob.exclude');
    expect(io.out.join('\n')).not.toContain('warning');
  });

  it('prints a warning when two classes pass the same decorator token', () => {
    const source = (name: string) =>
      `import { register } from 'ts-ioc-container';\n@register(Token)\nexport class ${name} {}\n`;
    project.write('src/services/A.ts', source('A'));
    project.write('src/services/B.ts', source('B'));
    const io = new Io(project.root);

    expect(run(['build', 'app.bundle.json'], io)).toBe(0);
    expect(io.err.join('\n')).toContain('tic: warning: app.bundle.json: decorator token "Token"');
  });

  it('prints usage for --help and rejects an unknown command', () => {
    const io = new Io(project.root);

    expect(run(['--help'], io)).toBe(0);
    expect(io.out.join('\n')).toContain('ts-ioc-container build [<config>]');
    expect(io.out.join('\n')).toContain('tic build app.bundle.json > src/di/app.bundle.ts');
    expect(io.out.join('\n')).toContain('tic is a shortcut for ts-ioc-container');
    expect(run(['compile'], io)).toBe(1);
    expect(io.err).toContain('tic: unknown command "compile"');
  });

  it('installs as ts-ioc-container, with tic as a shortcut to the same program', () => {
    const { bin } = JSON.parse(readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8'));

    expect(bin).toEqual({ 'ts-ioc-container': 'cjm/bin.js', tic: 'cjm/bin.js' });
  });
});
