import { build, DEFAULT_EXCLUDE, TicConfigError, NamespaceNotFoundError } from '../../lib';
import { symlinkSync } from 'node:fs';
import { decorated, TempProject } from '../project';

const module = (paths: unknown[], { files, ...extra }: { files?: object; [field: string]: unknown } = {}) => ({
  output: 'src/di/container.bundle.ts',
  files: { paths, ...files },
  ...extra,
});

describe('Folder registration', () => {
  let project: TempProject;

  afterEach(() => project?.dispose());

  const generated = () => project.read('src/di/container.bundle.ts');
  const buildProject = (options: { check?: boolean } = {}) =>
    build({ config: project.path('app.bundle.json'), ...options });

  describe('Story: Describe the container in a config file', () => {
    it('resolves relative paths against the config file, not the working directory', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services']),
        'src/services/Logger.ts': decorated('Logger'),
      });

      build({ config: project.path('app.bundle.json'), cwd: '/' });

      expect(generated()).toContain("import { Logger } from '../services/Logger';");
    });

    it.each([
      [{}, 'export class AppBundle implements IContainerModule'],
      [{ name: 'services' }, 'export class ServicesBundle implements IContainerModule'],
      [{ name: 'my-app_v2' }, 'export class MyAppV2Bundle implements IContainerModule'],
    ])('names the bundle class after the bundle name, by default the config file stem (%j)', (extra, expected) => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services'], extra),
        'src/services/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain(expected);
    });

    it('describes exactly one bundle: a bundles list is an unknown field', () => {
      project = TempProject.create({ 'app.bundle.json': { bundles: [module(['./src'])] } });

      expect(() => buildProject()).toThrow('bundles: unknown field');
    });

    it.each([
      [[], 'config: expected an object'],
      [{ files: { paths: ['./src'] } }, 'output: expected a non-empty string'],
      [module(['./src'], { output: '' }), 'output: expected a non-empty string'],
      [{ output: 'a.ts' }, 'files: expected an object'],
      [{ output: 'a.ts', files: {} }, 'files.paths: expected a non-empty array'],
      [{ output: 'a.ts', files: { include: ['**/*.ts'] } }, 'files.paths: expected a non-empty array'],
      [{ output: 'a.ts', files: 'src/**' }, 'files: expected an object'],
      [{ output: 'a.ts', files: { paths: [] } }, 'files.paths: expected a non-empty array'],
      [{ output: 'a.ts', files: { paths: [{ recursive: true }] } }, 'files.paths[0].path'],
      [module(['./src'], { name: 'not valid' }), 'name: expected letters, digits, "-" or "_", starting with a letter'],
      [module(['./src'], { name: '2fa' }), 'name: expected letters, digits, "-" or "_", starting with a letter'],
      [module(['./src'], { tags: ['production'] }), 'tags: unknown field'],
      [module(['./src'], { tsconfig: '' }), 'tsconfig: expected a non-empty string'],
      [module(['./src'], { extends: './tsconfig.json' }), 'extends: unknown field'],
      [{ output: 'a.ts', paths: ['./src'] }, 'paths: unknown field'],
      [{ output: 'a.ts', namespaces: ['./src'] }, 'namespaces: unknown field'],
      [module(['./src'], { include: './x.cjs' }), 'include: unknown field'],
      [module(['./src'], { select: {} }), 'select: unknown field'],
      [module(['./src'], { exclude: [] }), 'exclude: unknown field'],
      [module(['./src'], { compilerOptions: {} }), 'compilerOptions: unknown field'],
    ])('rejects an invalid config %j naming the field', (config, message) => {
      project = TempProject.create({ 'app.bundle.json': config });

      expect(() => buildProject()).toThrow(TicConfigError);
      expect(() => buildProject()).toThrow(message);
    });

    it('fails when the config file does not exist', () => {
      project = TempProject.create({});

      expect(() => buildProject()).toThrow(TicConfigError);
    });
  });

  describe('Story: Write the config in YAML', () => {
    const yaml = [
      'output: src/di/container.bundle.ts',
      'name: services',
      'files:',
      '  paths:',
      '    - ./src/services',
      'classes:',
      '  decorators: [register]',
      '',
    ].join('\n');

    it.each(['app.bundle.yaml', 'app.bundle.yml'])('reads %s like its JSON twin', (file) => {
      project = TempProject.create({ [file]: yaml, 'src/services/Logger.ts': decorated('Logger') });

      const { output } = build({ config: file, cwd: project.root });

      expect(output.bundle).toBe('ServicesBundle');
      expect(generated()).toContain('Registration.fromClass(Logger)');
      expect(generated()).toContain(`// Generated by \`tic build\` from ../../${file}.`);
    });

    it('rejects an empty YAML file: output and files must be written out', () => {
      project = TempProject.create({ 'production.bundle.yaml': '', 'tsconfig.json': { include: ['src'] } });

      expect(() => build({ config: 'production.bundle.yaml', cwd: project.root })).toThrow(
        'output: expected a non-empty string; files: expected an object',
      );
    });

    it.each([
      ['output: [unclosed', /app\.bundle\.yaml is not valid YAML/],
      ['- output: a.ts', 'config: expected an object'],
      ['output: a.ts\nselect: {}', 'select: unknown field'],
    ])('rejects %j naming the problem', (source, message) => {
      project = TempProject.create({ 'app.bundle.yaml': source });

      expect(() => build({ config: 'app.bundle.yaml', cwd: project.root })).toThrow(TicConfigError);
      expect(() => build({ config: 'app.bundle.yaml', cwd: project.root })).toThrow(message);
    });
  });

  describe('Story: Register the classes of a folder', () => {
    it('registers every decorated class of a folder recursively, ordered by file path', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services']),
        'src/services/b/UserService.ts': decorated('UserService'),
        'src/services/Auth.ts': `${decorated('AuthService')}\n@register()\nexport class TokenService {}\n`,
      });

      buildProject();

      expect(generated()).toContain(
        [
          'export const registrations: IRegistration[] = [',
          '  Registration.fromClass(AuthService),',
          '  Registration.fromClass(TokenService),',
          '  Registration.fromClass(UserService),',
          '];',
        ].join('\n'),
      );
    });

    it('limits a namespace to its own folder when recursive is false', () => {
      project = TempProject.create({
        'app.bundle.json': module([{ path: './src/services', recursive: false }]),
        'src/services/Logger.ts': decorated('Logger'),
        'src/services/nested/Hidden.ts': decorated('Hidden'),
      });

      buildProject();

      expect(generated()).toContain('Registration.fromClass(Logger)');
      expect(generated()).not.toContain('Hidden');
    });

    it('registers exported classes, skipping non-exported and abstract ones', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: [] } }),
        'src/Classes.ts': [
          "import { register } from 'ts-ioc-container';",
          'export class Plain {}',
          '@register() export class Decorated {}',
          '@register() class Private {}',
          '@register() export abstract class Base {}',
        ].join('\n'),
      });

      buildProject();

      expect(generated()).toMatch(/fromClass\(Plain\)[\s\S]*fromClass\(Decorated\)/);
      expect(generated()).not.toMatch(/Private|Base/);
    });

    it('imports classes exported by export lists and default exports under their exported name', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src']),
        'src/List.ts':
          "import { register } from 'ts-ioc-container';\n@register() class Local {}\nexport { Local as Listed };\n",
        'src/Default.ts': "import { register } from 'ts-ioc-container';\n@register() export default class Main {}\n",
      });

      buildProject();

      expect(generated()).toContain("import Main from '../Default';");
      expect(generated()).toContain("import { Listed } from '../List';");
    });

    it('never registers test files, declaration files or the generated output itself', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src']),
        'src/Kept.ts': decorated('Kept'),
        'src/Kept.spec.ts': decorated('KeptSpec'),
        'src/__tests__/Helper.ts': decorated('Helper'),
        'src/types.d.ts': 'export declare class Declared {}',
        'src/di/container.bundle.ts': decorated('Stale'),
      });

      buildProject();

      expect(generated()).toContain('Registration.fromClass(Kept)');
      expect(generated()).not.toMatch(/KeptSpec|Helper|Declared|Stale/);
    });

    it('replaces the default excludes with the configured globs', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { files: { exclude: ['src/legacy/**'] } }),
        'src/legacy/Old.ts': decorated('Old'),
        'src/Kept.spec.ts': decorated('KeptSpec'),
      });

      buildProject();

      expect(generated()).toContain('Registration.fromClass(KeptSpec)');
      expect(generated()).not.toContain('Old');
    });

    it('warns when a non-empty exclude drops the default test globs', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { files: { exclude: ['src/legacy/**'] } }),
        'src/legacy/Old.ts': decorated('Old'),
      });

      const { warnings } = buildProject();

      expect(warnings).toHaveLength(1);
      expect(warnings[0]).toContain('files.exclude');
      expect(warnings[0]).toContain('**/*.spec.ts');
      expect(warnings[0]).toContain('add them back');
    });

    it('does not warn for a complete exclude or an explicit empty exclude', () => {
      const cases = [{ files: { exclude: [...DEFAULT_EXCLUDE] } }, { files: { exclude: [] } }];

      for (const extra of cases) {
        project = TempProject.create({
          'app.bundle.json': module(['./src'], extra),
          'src/Kept.ts': decorated('Kept'),
        });

        expect(buildProject().warnings).toEqual([]);
      }
    });
  });

  describe('Story: Select files by name before parsing', () => {
    const sources = {
      'src/user.service.ts': decorated('UserService'),
      'src/user.repository.ts': decorated('UserRepository'),
      'src/legacy/old.service.ts': decorated('OldService'),
      'src/helpers.ts': decorated('Helper'),
    };
    const registered = () => [...generated().matchAll(/fromClass\((\w+)\)/g)].map(([, name]) => name);

    it('parses only files matching one of the include globs', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { files: { include: ['**/*.service.ts', '**/*.repository.ts'] } }),
        ...sources,
      });

      buildProject();

      expect(registered()).toEqual(['OldService', 'UserRepository', 'UserService']);
    });

    it('never reads a file outside the include globs', () => {
      // A dangling `.ts` symlink fails the build the moment it is read.
      const withBrokenFile = (files: object) => {
        project = TempProject.create({ 'app.bundle.json': module(['./src'], { files }), ...sources });
        symlinkSync(project.path('missing.ts'), project.path('src/broken.ts'));
      };

      withBrokenFile({});
      expect(() => buildProject()).toThrow(/ENOENT/);

      withBrokenFile({ include: ['**/*.service.ts'] });
      expect(() => buildProject()).not.toThrow();
    });

    it('drops files matching exclude even when include matches them', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], {
          files: { include: ['**/*.service.ts'], exclude: [...DEFAULT_EXCLUDE, 'src/legacy/**'] },
        }),
        ...sources,
      });

      buildProject();

      expect(registered()).toEqual(['UserService']);
    });

    it('keeps the default excludes when only include is given', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { files: { include: ['**/*.service.ts'] } }),
        'src/user.service.ts': decorated('UserService'),
        'src/user.service.spec.ts': decorated('UserServiceSpec'),
      });

      buildProject();

      expect(registered()).toEqual(['UserService']);
    });

    it('applies the class selector to the files that were parsed', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], {
          files: { include: ['**/*.service.ts'] },
          classes: { excludeName: 'Old*' },
        }),
        ...sources,
      });

      buildProject();

      expect(registered()).toEqual(['UserService']);
    });

    it.each([
      [{ include: [] }, 'files.include: expected a non-empty array of strings'],
      [{ include: [''] }, 'files.include: expected a non-empty array of strings'],
      [{ exclude: 'src/**' }, 'files.exclude: expected an array of strings'],
      [{ only: ['**/*.ts'] }, 'files.only: unknown field'],
    ])('rejects the file rule %j naming the field', (files, message) => {
      project = TempProject.create({ 'app.bundle.json': module(['./src'], { files }) });

      expect(() => buildProject()).toThrow(TicConfigError);
      expect(() => buildProject()).toThrow(message);
    });
  });

  describe('Story: Configure which classes a file contributes', () => {
    const classes = [
      "import { register } from 'ts-ioc-container';",
      'export class UserService {}',
      '@register() export class AuthService {}',
      'export class Helper {}',
      '@register() export default class MainService {}',
    ].join('\n');

    // Each criterion in isolation: `decorators: []` lifts the default @register requirement.
    const selected = (select: object) => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: [], ...select } }),
        'src/Classes.ts': classes,
      });
      buildProject();
      return [...generated().matchAll(/fromClass\((\w+)\)/g)].map(([, name]) => name);
    };

    it('registers classes decorated with @register by default', () => {
      project = TempProject.create({ 'app.bundle.json': module(['./src']), 'src/Classes.ts': classes });
      buildProject();

      expect([...generated().matchAll(/fromClass\((\w+)\)/g)].map(([, name]) => name)).toEqual([
        'AuthService',
        'MainService',
      ]);
    });

    it('lifts the decorator requirement with an empty decorators list', () => {
      expect(selected({ decorators: [] })).toEqual(['UserService', 'AuthService', 'Helper', 'MainService']);
    });

    it.each([
      [{ export: 'named' }, ['UserService', 'AuthService', 'Helper']],
      [{ export: 'default' }, ['MainService']],
    ])('restricts exports with %j', (select, expected) => {
      expect(selected(select)).toEqual(expected);
    });

    it('requires one of the listed decorators', () => {
      expect(selected({ decorators: ['register'] })).toEqual(['AuthService', 'MainService']);
    });

    it('requires the class name to match a glob', () => {
      expect(selected({ name: '*Service' })).toEqual(['UserService', 'AuthService', 'MainService']);
    });

    it('combines criteria: a class must meet every one', () => {
      expect(selected({ export: 'named', decorators: ['register'], name: '*Service' })).toEqual(['AuthService']);
    });

    it('recognises decorators by name through renamed imports and member access', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: ['register', 'service'] } }),
        'src/Renamed.ts': "import { register as reg } from 'ts-ioc-container';\n@reg() export class Renamed {}\n",
        'src/Member.ts': "import * as ioc from 'ts-ioc-container';\n@ioc.register() export class Member {}\n",
        'src/Custom.ts': "import { service } from './service';\n@service export class Custom {}\n",
        'src/Other.ts': "import { other } from './other';\n@other() export class Other {}\n",
      });

      buildProject();

      expect(generated()).toMatch(/fromClass\(Custom\)[\s\S]*fromClass\(Member\)[\s\S]*fromClass\(Renamed\)/);
      expect(generated()).not.toContain('Other');
    });

    it('matches the name of an anonymous default export by its file name', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: [], name: '*Service' } }),
        'src/user-service.ts': 'export default class {}\n',
      });

      buildProject();

      expect(generated()).toContain("import UserService from '../user-service';");
    });

    it('drops classes by exact name with excludeClasses', () => {
      expect(selected({ excludeClasses: ['Helper', 'AuthService'] })).toEqual(['UserService', 'MainService']);
    });

    it('drops classes whose name matches excludeName', () => {
      expect(selected({ excludeName: '*Service' })).toEqual(['Helper']);
    });

    it('applies exclusions after the positive criteria', () => {
      expect(selected({ decorators: ['register'], excludeClasses: ['MainService'] })).toEqual(['AuthService']);
    });

    it.each([
      ['decorated', 'classes: expected an object'],
      [{ export: 'all' }, 'classes.export: expected "any", "named" or "default"'],
      [{ decorators: [''] }, 'classes.decorators: expected an array of strings'],
      [{ name: '' }, 'classes.name: expected a non-empty string'],
      [{ excludeClasses: [] }, 'classes.excludeClasses: expected a non-empty array of strings'],
      [{ excludeName: '' }, 'classes.excludeName: expected a non-empty string'],
      [{ exported: true }, 'classes.exported: unknown field'],
      [{ nameGlob: '*Service' }, 'classes.nameGlob: unknown field'],
      [{ excludeNameGlob: '*Mock' }, 'classes.excludeNameGlob: unknown field'],
    ])('rejects the rule %j naming the field', (select, message) => {
      project = TempProject.create({ 'app.bundle.json': module(['./src'], { classes: select }) });

      expect(() => buildProject()).toThrow(TicConfigError);
      expect(() => buildProject()).toThrow(message);
    });
  });

  describe('Story: Warn about two classes binding the same token', () => {
    const repo = (name: string, token = 'IDashboardRepositoryToken') =>
      `import { repository } from 'ts-ioc-container';\n@repository(${token})\nexport class ${name} {}\n`;

    it('warns when two selected classes pass the same decorator identifier', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: ['repository'] } }),
        'src/HttpDashboardRepository.ts': repo('HttpDashboardRepository'),
        'src/MockDashboardRepository.ts': repo('MockDashboardRepository'),
      });

      const { warnings } = buildProject();

      expect(warnings).toHaveLength(1);
      expect(warnings[0]).toContain('decorator token');
      expect(warnings[0]).toContain('IDashboardRepositoryToken');
      expect(warnings[0]).toContain('HttpDashboardRepository, MockDashboardRepository');
      expect(warnings[0]).toContain('classes.excludeClasses');
    });

    it('does not warn once one colliding class is excluded', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], {
          classes: { decorators: ['repository'], excludeClasses: ['MockDashboardRepository'] },
        }),
        'src/HttpDashboardRepository.ts': repo('HttpDashboardRepository'),
        'src/MockDashboardRepository.ts': repo('MockDashboardRepository'),
      });

      expect(buildProject().warnings).toEqual([]);
      expect(generated()).not.toContain('MockDashboardRepository');
    });

    it('ignores decorators whose first argument is not a plain identifier', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: ['repository'] } }),
        'src/A.ts': decorated('A'),
        'src/B.ts': decorated('B'),
      });

      expect(buildProject().warnings).toEqual([]);
    });

    it('does not warn when a shared decorator scopes the colliding classes apart', () => {
      const scoped = (name: string, page: string) =>
        `import { repository } from 'ts-ioc-container';\n` +
        `import { perPage } from './scope';\n` +
        `@repository(IFilterChipsToken)\n@perPage('${page}')\nexport class ${name} {}\n`;
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: ['repository'] } }),
        'src/StationFilterChips.ts': scoped('StationFilterChips', 'stations'),
        'src/SessionFilterChips.ts': scoped('SessionFilterChips', 'sessions'),
      });

      expect(buildProject().warnings).toEqual([]);
    });

    it('still warns when the shared decorator has the same argument', () => {
      const scoped = (name: string) =>
        `import { repository } from 'ts-ioc-container';\n` +
        `import { perPage } from './scope';\n` +
        `@repository(IFilterChipsToken)\n@perPage('stations')\nexport class ${name} {}\n`;
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { classes: { decorators: ['repository'] } }),
        'src/A.ts': scoped('A'),
        'src/B.ts': scoped('B'),
      });

      expect(buildProject().warnings).toHaveLength(1);
    });
  });

  describe('Story: Name every input explicitly', () => {
    const registered = () => [...generated().matchAll(/fromClass\((\w+)\)/g)].map(([, name]) => name);

    it('never takes files from the tsconfig: only files.paths are scanned', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./lib']),
        'tsconfig.json': { include: ['src'] },
        'src/App.ts': decorated('App'),
        'lib/External.ts': decorated('External'),
      });

      buildProject();

      expect(registered()).toEqual(['External']);
    });

    it('writes the folders it scanned into the header of the bundle', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services', '@app/infra']),
        'tsconfig.json': { compilerOptions: { paths: { '@app/*': ['./src/*'] } } },
        'src/services/Logger.ts': decorated('Logger'),
        'src/infra/Db.ts': decorated('Db'),
      });

      buildProject();

      expect(generated()).toContain('// Paths: ./src/services, @app/infra');
    });

    it('requires a name when the config file is not named <name>.bundle.json', () => {
      project = TempProject.create({
        'bundle.json': module(['./src']),
        'named.json': module(['./src'], { name: 'admin' }),
        'src/Logger.ts': decorated('Logger'),
      });

      expect(() => build({ config: 'bundle.json', cwd: project.root })).toThrow(TicConfigError);
      expect(() => build({ config: 'bundle.json', cwd: project.root })).toThrow(/^name: required/);
      expect(build({ config: 'named.json', cwd: project.root }).output.bundle).toBe('AdminBundle');
    });
  });

  describe('Story: Address folders by tsconfig aliases', () => {
    const tsconfig = (compilerOptions: object) => ({ compilerOptions });

    it('resolves an alias namespace through inherited tsconfig paths and imports in alias form', () => {
      project = TempProject.create({
        'app.bundle.json': module(['@app/services', './lib']),
        'tsconfig.base.json': tsconfig({ paths: { '@app/*': ['./src/*'], '@services/*': ['./src/services/*'] } }),
        'tsconfig.json': { extends: './tsconfig.base.json' },
        'src/services/Logger.ts': decorated('Logger'),
        'lib/External.ts': decorated('External'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '@services/Logger';");
      expect(generated()).toContain("import { External } from '../../lib/External';");
    });

    it('reads the aliases of the tsconfig named in the config', () => {
      project = TempProject.create({
        'app.bundle.json': module(['@app/services'], { tsconfig: './tsconfig.app.json' }),
        'tsconfig.app.json': tsconfig({ baseUrl: '.', paths: { '@app/*': ['src/*'] } }),
        'src/services/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '@app/services/Logger';");
    });

    it('fails when the tsconfig it explicitly names does not exist', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src'], { tsconfig: './tsconfig.app.json' }),
        'src/Logger.ts': decorated('Logger'),
      });

      expect(() => buildProject()).toThrow(TicConfigError);
      expect(() => buildProject()).toThrow(/tsconfig not found: .*tsconfig\.app\.json/);
    });

    it('builds without a tsconfig when it names none and there is no tsconfig.json', () => {
      project = TempProject.create({ 'app.bundle.json': module(['./src']), 'src/Logger.ts': decorated('Logger') });

      buildProject();

      expect(generated()).toContain("import { Logger } from '../Logger';");
    });

    it('fails naming a namespace that is neither a folder nor an alias', () => {
      project = TempProject.create({
        'app.bundle.json': module(['@app/missing']),
        'tsconfig.json': tsconfig({ paths: { '@app/*': ['./src/*'] } }),
      });

      expect(() => buildProject()).toThrow(NamespaceNotFoundError);
      expect(() => buildProject()).toThrow('@app/missing');
    });

    it('adds a .js extension under nodenext resolution', () => {
      project = TempProject.create({
        'app.bundle.json': module(['@app/services']),
        'tsconfig.json': tsconfig({
          module: 'nodenext',
          moduleResolution: 'nodenext',
          paths: { '@app/*': ['./src/*'] },
        }),
        'src/services/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '@app/services/Logger.js';");
    });

    it('lets importExtension override the inferred extension', () => {
      project = TempProject.create({
        'app.bundle.json': { importExtension: '', ...module(['./src/services']) },
        'tsconfig.json': tsconfig({ module: 'nodenext', moduleResolution: 'nodenext' }),
        'src/services/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '../services/Logger';");
    });
  });

  describe('Story: Generate a plain container module', () => {
    it('imports same-named classes under distinct local names', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src']),
        'src/a/Logger.ts': decorated('Logger'),
        'src/b/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '../a/Logger';");
      expect(generated()).toContain("import { Logger as Logger_2 } from '../b/Logger';");
      expect(generated()).toContain('Registration.fromClass(Logger_2)');
    });
  });

  describe('Story: Generate a plain container module (protocol)', () => {
    it('writes paths into the generated TypeScript verbatim, never HTML-escaped', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/a&b']),
        'src/a&b/Logger.ts': decorated('Logger'),
      });

      buildProject();

      expect(generated()).toContain("import { Logger } from '../a&b/Logger';");
      expect(generated()).not.toMatch(/&amp;|&#x27;|&quot;/);
    });
  });

  describe('Story: Keep bundles in sync in CI', () => {
    it('reports a missing or outdated output as stale without writing it', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services']),
        'src/services/Logger.ts': decorated('Logger'),
      });

      const result = buildProject({ check: true });

      expect(result.output.status).toBe('stale');
      expect(() => generated()).toThrow();
    });

    it('leaves an up-to-date output untouched', () => {
      project = TempProject.create({
        'app.bundle.json': module(['./src/services']),
        'src/services/Logger.ts': decorated('Logger'),
      });

      expect(buildProject().output.status).toBe('written');
      expect(buildProject().output.status).toBe('unchanged');
      expect(buildProject({ check: true }).output.status).toBe('unchanged');
    });
  });
});
