// Generated by `tic build` from tsconfig.json. Do not edit by hand.
// Files: as compiled by tsconfig.json
import { type IContainer, type IContainerModule, type IRegistration } from 'ts-ioc-container';

export const registrations: IRegistration[] = [];

export class BaseBundle implements IContainerModule {
  applyTo(container: IContainer): void {
    for (const registration of registrations) container.addRegistration(registration);
  }
}
