import type { DiscoveredClass } from './scan';

export interface EmitInput {
  /** Name of the exported `IContainerModule`. */
  name: string;
  /** Shown in the header: where the output came from. */
  configPath: string;
  namespaces: string[];
  classes: (DiscoveredClass & { specifier: string })[];
}

const RUNTIME_IMPORTS = ['IContainer', 'IContainerModule', 'IRegistration', 'Registration'];

/** Renders the generated module: static imports, `registrations`, and the module applying them. */
export function emitModule({ name, configPath, namespaces, classes }: EmitInput): string {
  const taken = new Set([...RUNTIME_IMPORTS, 'registrations', name]);
  const uniqueName = (wanted: string) => {
    let candidate = wanted;
    for (let n = 2; taken.has(candidate); n++) candidate = `${wanted}_${n}`;
    taken.add(candidate);
    return candidate;
  };

  // One import statement per file, in file order.
  const byFile = new Map<string, { specifier: string; defaultName?: string; named: string[] }>();
  const bindings = classes.map((cls) => {
    const binding = uniqueName(cls.localName);
    const entry = byFile.get(cls.file) ?? { specifier: cls.specifier, named: [] };
    byFile.set(cls.file, entry);
    if (cls.exportName === 'default') entry.defaultName = binding;
    else entry.named.push(binding === cls.exportName ? binding : `${cls.exportName} as ${binding}`);
    return binding;
  });

  const runtime = classes.length > 0 ? ', Registration' : '';
  const lines = [
    `// Generated by \`tic build\` from ${configPath}. Do not edit by hand.`,
    `// Namespaces: ${namespaces.join(', ')}`,
    `import { type IContainer, type IContainerModule, type IRegistration${runtime} } from 'ts-ioc-container';`,
    ...[...byFile.values()].map(({ specifier, defaultName, named }) => {
      const parts = [defaultName, named.length > 0 ? `{ ${named.join(', ')} }` : undefined].filter(Boolean);
      return `import ${parts.join(', ')} from '${specifier}';`;
    }),
    '',
    classes.length === 0
      ? 'export const registrations: IRegistration[] = [];'
      : [
          'export const registrations: IRegistration[] = [',
          ...bindings.map((b) => `  Registration.fromClass(${b}),`),
          '];',
        ].join('\n'),
    '',
    `export const ${name}: IContainerModule = {`,
    '  applyTo(container: IContainer): void {',
    '    for (const registration of registrations) container.addRegistration(registration);',
    '  },',
    '};',
    '',
  ];
  return lines.join('\n');
}
