export const USAGE = [
  'Usage: ts-ioc-container <command> [options]',
  '       tic is a shortcut for ts-ioc-container',
  '',
  'Commands:',
  '  ts-ioc-container build [<config>]   print the bundle a config file (.json, .yaml, .yml) describes;',
  '                                     without one (or with -), read the config from stdin',
  '  ts-ioc-container help               show this help',
  '  ts-ioc-container version            show the version',
  '',
  'Options:',
  '  -h, --help      show this help',
  '  -v, --version   show the version',
  '',
  'The bundle goes to stdout and warnings to stderr; saving it is up to you:',
  '  tic build app.bundle.json > src/di/app.bundle.ts',
  '  cat app.bundle.yml | tic build > src/di/app.bundle.ts     # config from stdin (must set name)',
  '  tic build app.bundle.json | diff - src/di/app.bundle.ts   # CI: is it current?',
].join('\n');
