export const USAGE = [
  'Usage: ts-ioc-container <command> [options]',
  '       tic is a shortcut for ts-ioc-container',
  '',
  'Commands:',
  '  ts-ioc-container build <output> (--json <content> | --yaml <content>) [--check]',
  '                                       generate the bundle <output> from config content',
  '  ts-ioc-container help                show this help',
  '  ts-ioc-container version             show the version',
  '',
  'Options:',
  '  --json <content>   the bundle config as JSON; - reads it from stdin',
  '  --yaml <content>   the bundle config as YAML; - reads it from stdin',
  '  --check            write nothing; exit 1 when the generated bundle is out of date',
  '  -h, --help         show this help',
  '  -v, --version      show the version',
  '',
  'The config is content, never a path: read it yourself.',
  '  tic build src/di/app.bundle.ts --json "$(cat app.bundle.json)"',
  '  cat prod.bundle.yml | tic build src/di/prod.bundle.ts --yaml -',
].join('\n');
