import { z } from 'zod';
import { BUNDLE_CONFIG_SCHEMA } from '../features/build/BuildConfig';

/**
 * The JSON Schema published as `tic.schema.json`, generated from the zod schema
 * `tic build` validates with. `pnpm run generate:schema` writes it; a test fails
 * when the committed file is stale.
 */
export function ticConfigJsonSchema(): Record<string, unknown> {
  const schema = z.toJSONSchema(BUNDLE_CONFIG_SCHEMA, {
    io: 'input',
    target: 'draft-7',
    // String lists are custom checks; their shape comes from `.meta()`.
    unrepresentable: 'any',
    // Editors flag unknown fields everywhere; the CLI tolerates them inside a `files.paths` entry.
    override: ({ jsonSchema }) => {
      if (jsonSchema.type === 'object') jsonSchema.additionalProperties = false;
    },
  });
  const { $schema, ...rest } = schema;
  return {
    $schema,
    $id: 'https://github.com/IgorBabkin/ts-ioc-container/tree/main/packages/bundler/tic.schema.json',
    title: '*.bundle.json / *.bundle.yaml',
    description:
      "One bundle generated by `tic build` (@ts-ioc-container/bundler). `tic build` builds every `*.bundle.json` / `*.bundle.yaml` / `*.bundle.yml` at the root of the package it is invoked in, or — with none — one bundle from that package's tsconfig.json with every setting at its default. Relative paths resolve against this file's directory.",
    ...rest,
  };
}
