import { z } from 'zod';
import { BUNDLE_CONFIG_SCHEMA } from '../features/build/BuildConfig';

/**
 * The JSON Schema published as `tic.schema.json`, generated from the zod schema
 * `tic build` validates with. `pnpm run generate:schema` writes it; a test fails
 * when the committed file is stale.
 */
export function ticConfigJsonSchema(): Record<string, unknown> {
  const schema = z.toJSONSchema(BUNDLE_CONFIG_SCHEMA, {
    io: 'input',
    target: 'draft-7',
    // String lists are custom checks; their shape comes from `.meta()`.
    unrepresentable: 'any',
    // Editors flag unknown fields everywhere; the CLI tolerates them inside a `glob.paths` entry.
    override: ({ jsonSchema }) => {
      if (jsonSchema.type === 'object') jsonSchema.additionalProperties = false;
    },
  });
  const { $schema, ...rest } = schema;
  return {
    $schema,
    $id: 'https://github.com/IgorBabkin/ts-ioc-container/tree/main/packages/bundler/tic.schema.json',
    title: '*.bundle.json / *.bundle.yaml',
    description:
      "One bundle generated by `tic build` (@ts-ioc-container/bundler). Its content is handed over as `tic build <output> --json '<content>'` or `--yaml '<content>'`; wherever it is kept, reading it is the caller's job. Relative paths resolve against the working directory.",
    ...rest,
  };
}
