name: pull-request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload-build-output: false  # nothing downstream consumes it on a PR
